version: 0.2
env:
  variables:
      IMAGE_TAG: $(git log -1 --format=%h)
phases:
  pre_build:
    commands:
      - echo logging into ECR
      - $(aws ecr get-login --no-include-email --region us-east-1)
  build:
    commands:
      - echo Build started
      - echo Building the Docker Image
      - docker build -t demorepo .
      - docker tag demorepo:$IMAGE_TAG 488599217855.dkr.ecr.us-east-1.amazonaws.com/demorepo:latest
  post_build:
    commands:
      - echo Build completed
      - echo pushing the Docker image
      - docker push 488599217855.dkr.ecr.us-east-1.amazonaws.com/demorepo:latest
